---
- name: Launch EC2 instance with Security Group and Key Pair
  hosts: localhost
  connection: local
  gather_facts: False

  collections:
    - amazon.aws

  vars:
    region: us-east-1
    instance_type: t2.micro
    ami: ami-0ac019f4fcb7cb7e6    # Ubuntu Server 18.04 LTS (us-east-1)
    key_name: myNewKeyPair
    volume_size: 20
    volume_type: gp2
    security_group_name: mySecurityGroup
    ssh_cidr: 0.0.0.0/0

  tasks:

    - name: Create SSH key pair
      amazon.aws.ec2_key:
        name: "{{ key_name }}"
        region: "{{ region }}"
        state: present
      register: keypair_result

    - name: Save private key to file
      copy:
        content: "{{ keypair_result.key.private_key }}"
        dest: "./{{ key_name }}.pem"
        mode: '0600'
      when: keypair_result.changed

    - name: Create security group
      amazon.aws.ec2_group:
        name: "{{ security_group_name }}"
        description: "Allow SSH, HTTP, HTTPS"
        region: "{{ region }}"
        rules:
          - proto: tcp
            ports:
              - 22
              - 80
              - 443
            cidr_ip: "{{ ssh_cidr }}"
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0

    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        name: myUbuntuInstance
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami }}"
        wait: yes
        region: "{{ region }}"
        volumes:
          - device_name: /dev/sda1
            ebs:
              volume_size: "{{ volume_size }}"
              volume_type: "{{ volume_type }}"
              delete_on_termination: true
        vpc_subnet_id: null     # Use default subnet
        security_groups: [ "{{ security_group_name }}" ]
      register: ec2

    - name: Show instance public IP
      debug:
        msg: "Instance public IP: {{ ec2.instances[0].public_ip_address }}"
