- name: Create cluster role for postgres statefulsets
  kubernetes.core.k8s:
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: postgres-access
      rules:
        - apiGroups: ["apps"]
          resources: ["statefulsets"]
          verbs: ["get", "list", "exec"]
 
- name: Bind cluster role to user Eren
  kubernetes.core.k8s:
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: postgres-access-binding
      subjects:
        - kind: User
          name: Eren
          apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: postgres-access
        apiGroup: rbac.authorization.k8s.io
